# Generated by Django 4.2.1 on 2023-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_autor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(default='anonimo', max_length=100),
        ),
    ]
