# Generated by Django 4.2.1 on 2023-05-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0003_alter_autor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
